### ISSUE TITLE
/usr/pgsql-9.6/lib/pg_stat_kcache.so: undefined symbol: RequestAddinLWLocks

### ISSUE THREAD

**Issue by isaiasanchez** [dalibo/pg_stat_kcache#10]
I was unable to start a 9.6 cluster with this extension, I must remove it compltely.

ERROR:  could not load library "/usr/pgsql-9.6/lib/pg_stat_kcache.so": /usr/pgsql-9.6/lib/pg_stat_kcache.so: undefined symbol: RequestAddinLWLocks

**Comment by isaiasanchez** [comment]
It was installed using pgdg repository on centos 6

**Comment by rjuju** [comment]
Hi,

This has been fixed long time ago (see commit https://github.com/dalibo/pg_stat_kcache/commit/58c34e75667d3f6786c2d6338c5317fb09dfe946), but never released.  I just released version 2.0.3 which should solve your issue.  Unless you're willing to compile it, you'll have to wait for the rpm packager to update to this version.

Sorry about that, and thanks for warning us about this issue.

Regards

**Comment by frost242** [comment]
We should already have closed this issue. Doing it right now.
