### ISSUE TITLE
Attempt to create **pg_stat_kcache** extension forcibly switch **check_function_bodies** parameter to **false**.

### ISSUE THREAD

**Issue by rus21** [dalibo/pg_stat_kcache#9]
Attempt to create **pg_stat_kcache** extension forcibly switch **check_function_bodies** parameter to **false**.
```SQL
    CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;
    COMMENT ON EXTENSION pg_stat_statements IS 'track execution statistics of all SQL statements executed';
    SET check_function_bodies = false;
    show check_function_bodies; *--false

    CREATE EXTENSION IF NOT EXISTS pg_stat_kcache WITH SCHEMA public;
    COMMENT ON EXTENSION pg_stat_kcache IS 'Kernel cache statistics gathering';
    show check_function_bodies; *--true
```

**Comment by rjuju** [comment]
Hello,

Indeed the extension set this parameter to on while installing. Commit d7734fb8ce60f8d8ce3fa9efae627c9c730c9488 should fix this issue.

Thanks for the report.

Regards.

**Comment by rus21** [comment]
Hello Julien!
It ought to tell what this microbug was found during the restore of pg_dump script of database with your extension installed.
Best wishes from participant of your presentation at Pgconf.Russia.2015!
Regards.
